// <auto-generated />
using System;
using CustomerIssuesManager.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerIssuesManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadedById")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerformedByName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("PerformedById");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionsTaken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DebtAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastMeterReading")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReadingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SolvedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriberNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("SolvedById");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.Correspondence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sender")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearlySequenceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Correspondences");
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformanceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceNumber")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "مدير النظام",
                            PerformanceNumber = 1,
                            Position = "Admin"
                        });
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.IssueCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("IssueCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "عبث بالعداد",
                            ColorCode = "#e74c3c",
                            Description = "التلاعب في قراءات العداد أو كسره"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "توصيلات غير شرعية",
                            ColorCode = "#e67e22",
                            Description = "توصيلات غاز غير مرخصة"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "خطأ قراءة",
                            ColorCode = "#f39c12",
                            Description = "خطأ في قراءة العداد"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "مشكلة فواتير",
                            ColorCode = "#9b59b6",
                            Description = "مشاكل في الفواتير والمدفوعات"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "تغيير نشاط",
                            ColorCode = "#3498db",
                            Description = "طلب تغيير نوع النشاط"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "تصحيح رقم عداد",
                            ColorCode = "#1abc9c",
                            Description = "تصحيح أرقام العدادات"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "نقل رقم مشترك",
                            ColorCode = "#2ecc71",
                            Description = "نقل الاشتراك لموقع آخر"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "كسر بالشاشة",
                            ColorCode = "#e74c3c",
                            Description = "كسر أو تلف شاشة العداد"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "عطل عداد",
                            ColorCode = "#c0392b",
                            Description = "أعطال فنية في العداد"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "هدم وازالة",
                            ColorCode = "#7f8c8d",
                            Description = "طلبات هدم أو إزالة التوصيلات"
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "أخرى",
                            ColorCode = "#95a5a6",
                            Description = "مشاكل أخرى غير مصنفة"
                        });
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.Attachment", b =>
                {
                    b.HasOne("CustomerIssuesManager.Core.Models.Case", "Case")
                        .WithMany("Attachments")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerIssuesManager.Core.Models.Employee", "UploadedBy")
                        .WithMany("Attachments")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.AuditLog", b =>
                {
                    b.HasOne("CustomerIssuesManager.Core.Models.Case", "Case")
                        .WithMany("AuditLogs")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerIssuesManager.Core.Models.Employee", "PerformedBy")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.Case", b =>
                {
                    b.HasOne("CustomerIssuesManager.Core.Models.IssueCategory", "Category")
                        .WithMany("Cases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerIssuesManager.Core.Models.Employee", "CreatedBy")
                        .WithMany("CreatedCases")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerIssuesManager.Core.Models.Employee", "ModifiedBy")
                        .WithMany("ModifiedCases")
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CustomerIssuesManager.Core.Models.Employee", "SolvedBy")
                        .WithMany("SolvedCases")
                        .HasForeignKey("SolvedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("SolvedBy");
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.Correspondence", b =>
                {
                    b.HasOne("CustomerIssuesManager.Core.Models.Case", "Case")
                        .WithMany("Correspondences")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerIssuesManager.Core.Models.Employee", "CreatedBy")
                        .WithMany("Correspondences")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.Case", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("AuditLogs");

                    b.Navigation("Correspondences");
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.Employee", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("AuditLogs");

                    b.Navigation("Correspondences");

                    b.Navigation("CreatedCases");

                    b.Navigation("ModifiedCases");

                    b.Navigation("SolvedCases");
                });

            modelBuilder.Entity("CustomerIssuesManager.Core.Models.IssueCategory", b =>
                {
                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
